-- AlterTable
ALTER TABLE "Device" ADD COLUMN IF NOT EXISTS "totalStorageBytes" BIGINT;
ALTER TABLE "Device" ADD COLUMN IF NOT EXISTS "ramAvailBytes" BIGINT;
ALTER TABLE "Device" ADD COLUMN IF NOT EXISTS "ramTotalBytes" BIGINT;
ALTER TABLE "Device" ADD COLUMN IF NOT EXISTS "cpuUsagePercent" DOUBLE PRECISION;
ALTER TABLE "Device" ADD COLUMN IF NOT EXISTS "uptimeMs" BIGINT;
